### ISSUE TITLE
Allow scheduling checks for new versions of existing platforms and extensions

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/registry.quarkus.io#1]
Create a (daily?) scheduler that checks Maven Central for new versions of existing platforms and extensions. 

Introduce a column enabling the platform or individual extension for automatic updates

**Comment by gastaldi** [comment]
Any thoughts? /cc @maxandersen @aloubyansky

**Comment by aloubyansky** [comment]
Could the registry repo be notified whenever a registered platform or extension is released instead?

**Comment by gastaldi** [comment]
@aloubyansky sure, the `AdminEndpoint` is here for that reason.

**Comment by gastaldi** [comment]
For clarification: this should be a standalone service since the registry app does not (and should not) rely on external network resources (like Maven repostiories)

**Comment by aloubyansky** [comment]
Assuming we get the notifications from the corresponding repos about the releases, would this service still be useful?

**Comment by aloubyansky** [comment]
IMO, they should just set the "push the update" thing or submit the changes manually.

**Comment by gastaldi** [comment]
Ok, I'll close this in the meantime. We can revisit later if necessary
