### ISSUE TITLE
Enable latency histogram 

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/registry.quarkus.io#195]
This is a follow-up to https://github.com/quarkusio/registry.quarkus.io/pull/192

- [ ] Change the metrics code to get the histogram instead of the summary
- [ ] Make sure that you add a label in the metric that helps you differentiating read and write paths. The current metric has method and uri labels and that would definitely help to do what we need here. See https://prometheus.app-sre-prod-01.devshift.net/graph?g0.expr=http_server_requests_seconds_sum%7Bnamespace%3D%22registry-quarkus-redhat-production%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h

See https://issues.redhat.com/browse/APPSRE-4113 and https://redhat-internal.slack.com/archives/C02CMTM9GG1/p1683639385959459 for more details

**Comment by gastaldi** [comment]
@holly-cummins is this something you could have a look at?

**Comment by gastaldi** [comment]
Asking because I'll be on vacation until May 30th

**Comment by holly-cummins** [comment]
Hm, I've had a quick look, and if I try to access  https://prometheus.app-sre-prod-01.devshift.net/graph?g0.expr=http_server_requests_seconds_sum%7Bnamespace%3D%22registry-quarkus-redhat-production%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h, I get "An authentication error occurred."

I assume I don't have access, but I'll try again next week in case it's a transient error.

**Comment by gastaldi** [comment]
Ah you need to be added in the AppSRE team in the Gitlab Ops infrastructure. 

@ia3andy can you add Holly to the Quarkus team in the AppSRE YAMLs so she has access to the Quarkus Registry services?

**Comment by gastaldi** [comment]
Regardless, you can see what's being produced by hitting http://localhost:8080/q/metrics
