### ISSUE TITLE
Platform extensions are listed in non-platform extension catalogs

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/registry.quarkus.io#21]
E.g. https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-non-platform-extensions/1.0-SNAPSHOT/quarkus-non-platform-extensions-1.0-SNAPSHOT-2.1.0.Final.Final.json
includes all the platform extensions (right at the beginning, blaze persistence, cassandra, hazelvast, debezium, etc).
Ideally, platform extensions should not be listed in non-platform catalogs.

**Comment by gastaldi** [comment]
The Database had some wrong data (probably a residue from 1.x platform deployments). After deleting the stale rows the data is now back to normal
