### ISSUE TITLE
Parameterize properties in the registry descriptor

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/registry.quarkus.io#23]
Some descriptor properties are hardcoded. They should be parameterized: 

- [x] Group Id
- [x] Support for non-platforms
- [ ] RegistryQuarkusVersionsConfig

**Comment by aloubyansky** [comment]
/io/quarkus/registry/ is the groupId path. Which is also the reversed host name, by default, i.e. registry.quarkus.io.
So if we plan something like registry.quarkus.redhat.com as the host name then the groupId should be com.redhat.quarkus.registry and the path - com/redhat/quarkus/registry.
