### ISSUE TITLE
Maven Metadata Endpoint(s) returns 404

### ISSUE THREAD

**Issue by raphael-gosteli** [quarkusio/registry.quarkus.io#232]
While attempting to set up registry.quarkus.io as a Nexus Repository Proxy following the instructions in README.md, the publishing check fails with an "Item Not Found" Exception. The issue originates from the URL https://registry.quarkus.io/maven/.meta/repository-metadata.xml, leading to an unpublished proxy. A 404 error is encountered when using the curl command on the mentioned URL:

```
curl -vk https://registry.quarkus.io/maven/.meta/repository-metadata.xml
* About to connect() to registry.quarkus.io port 443 (#0)
*   Trying 193.247.43.169...
* Connected to registry.quarkus.io (193.247.43.169) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=prod1.redhat.com,O="Red Hat, Inc.",L=Raleigh,ST=North Carolina,C=US
* 	start date: Nov 17 00:00:00 2023 GMT
* 	expire date: Sep 26 23:59:59 2024 GMT
* 	common name: prod1.redhat.com
* 	issuer: CN=DigiCert TLS RSA SHA256 2020 CA1,O=DigiCert Inc,C=US
> GET /maven/.meta/repository-metadata.xml HTTP/1.1
> User-Agent: curl/7.29.0
> Host: registry.quarkus.io
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Type: text/html
< Content-Length: 13
< Cache-Control: max-age=0
< Date: Tue, 09 Jan 2024 12:25:49 GMT
< Connection: keep-alive
< x-rh-edge-request-id: 54d18d57
< x-rh-edge-reference-id: 0.a52bf7c1.1704803149.54d18d57
< x-rh-edge-cache-status: Constructed from child
<
* Connection #0 to host registry.quarkus.io left intact
404 Not Found
```

My preliminary assumption is that there might be an infrastructure or deployment issue, given that the tests against this endpoint in the application code are executing successfully.

I would appreciate it if you could verify whether the endpoint is configured correctly.

**Comment by gastaldi** [comment]
@raphael-gosteli indeed it was an infrastructure issue. I just fixed and it should be okay now. Thank you for reporting this!
