### ISSUE TITLE
Non-platform catalogs are missing the quarkus-core-version

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/registry.quarkus.io#27]
If you open
https://repo1.maven.org/maven2/io/quarkus/platform/quarkus-bom-quarkus-platform-descriptor/2.1.3.Final/quarkus-bom-quarkus-platform-descriptor-2.1.3.Final-2.1.3.Final.json
at the very bottom you'll find `"quarkus-core-version": "2.1.3.Final"`

but for example https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-non-platform-extensions/1.0-SNAPSHOT/quarkus-non-platform-extensions-1.0-SNAPSHOT-2.1.3.Final.json
is missing it.

**Comment by gastaldi** [comment]
Fixed and deployed 👍🏻 Thanks for reporting this

**Comment by aloubyansky** [comment]
That was super fast, thanks a lot!
