### ISSUE TITLE
Non-platform extension catalog IDs are wrong

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/registry.quarkus.io#31]
Looking at https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-non-platform-extensions/1.0-SNAPSHOT/quarkus-non-platform-extensions-1.0-SNAPSHOT-2.2.1.Final.json
````
"id": "io.quarkus.registry:quarkus-non-platform-extensions:2.2.1.Final:json:quarkus-registry-descriptor"
````
should be
````
"id": "io.quarkus.registry:quarkus-non-platform-extensions:2.2.1.Final:json:1.0-SNAPSHOT"
````

Also, by mistake, I first tried (swapping the classifier with the version in the file name) https://registry.quarkus.io/maven/io/quarkus/registry/quarkus-non-platform-extensions/1.0-SNAPSHOT/quarkus-non-platform-extensions-2.2.1.Final-1.0-SNAPSHOT.json
which returned
````
"id": "io.quarkus.registry:quarkus-non-platform-extensions:SNAPSHOT.Final:json:quarkus-registry-descriptor",
"bom": "io.quarkus.platform:quarkus-bom::pom:SNAPSHOT.Final",
````
Notice the `SNAPSHOT.Final` in place of the version BOM.

**Comment by gastaldi** [comment]
You're right, the static version is correct: https://quarkus-registry.netlify.app/maven/io/quarkus/registry/quarkus-non-platform-extensions/1.0-SNAPSHOT/quarkus-non-platform-extensions-1.0-SNAPSHOT-2.2.1.Final.json
