### ISSUE TITLE
registry.quarkus.redhat.com should promote the 2.7 stream once it's available in addition to 2.2

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/registry.quarkus.io#66]
At least until 2.2 becomes officially not supported.

**Comment by maxandersen** [comment]
isn't 2.5 coming bevfore 2.7?

**Comment by gastaldi** [comment]
What 2.7 stream are you referring to? The community one? If so, isn't that supposed to be returned from registry.quarkus.io only?

**Comment by aloubyansky** [comment]
No, as the title says it's about registry.quarkus.redhat.com promoting the 2.7 product stream once it's available in addition to 2.2. Perhaps, that's a not an issue actually. But that's what we were talking about as a requirement. AFAIU, there should be a time window when both 2.2 and 2.7 should be available. Once 2.2 becomes unsupported (a couple of month), it should probably get unlisted, leaving only 2.7 as the recommended stream.

**Comment by gastaldi** [comment]
One option is to completely remove the unsupported platform release from the registry, but I am not sure if that is desired. 

Another option is to introduce a column in the `platform_release` (or the `platform_stream`) table indicating if it's visible

**Comment by gastaldi** [comment]
I created #72 introducing a new `unlisted` column in platform streams. This will provide the ability to hide streams from the queries when they are no longer needed.
