### ISSUE TITLE
Weird Strict-Transport-Security max-age value

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/registry.quarkus.io#82]
https://github.com/quarkusio/registry.quarkus.io/blob/937bfc0d309099d46db04276dedfe2f3ee3e462c/src/main/resources/application.properties#L24

It seems 360 is not a good value for `max-age`, 1 year would be `max-age=31536000`:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

**Comment by ia3andy** [comment]
max-age=<expire-time>
The time, in seconds, that the browser should remember that a site is only to be accessed using HTTPS.

**Comment by gastaldi** [comment]
@ia3andy thanks for the ticket! Want to submit a PR fixing this?
